#include "rcc.h"

void rcc_init(void)
{
	RCC->CR |= RCC_CR_HSEON;
	while(!(RCC->CR & RCC_CR_HSERDY));

	FLASH->ACR |= FLASH_ACR_LATENCY_2WS | FLASH_ACR_ICEN | FLASH_ACR_DCEN | FLASH_ACR_PRFTEN;

	RCC->PLLCFGR = 0;
	RCC->PLLCFGR |= (8U << RCC_PLLCFGR_PLLM_Pos);
	RCC->PLLCFGR |= (336U << RCC_PLLCFGR_PLLN_Pos);
	RCC->PLLCFGR |= (1U << RCC_PLLCFGR_PLLP_Pos);

	RCC->PLLCFGR |= RCC_PLLCFGR_PLLSRC_HSE;
	RCC->CR |= RCC_CR_PLLON;
	while(!(RCC->CR & RCC_CR_PLLRDY));

	RCC->CFGR &= ~(RCC_CFGR_HPRE);
	RCC->CFGR &= ~(RCC_CFGR_PPRE1);
	RCC->CFGR &= ~(RCC_CFGR_PPRE2);

	RCC->CFGR |= RCC_CFGR_PPRE1_DIV2;

	RCC->CFGR &= ~(RCC_CFGR_SW);
	RCC->CFGR |= RCC_CFGR_SW_PLL;
	while((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL);
}
